version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '80:80'
     - '443:443'
    links:
     - sync
     - radicale
    restart: always
    environment:
      DOMAINS: 'radicale.freddieridell.com -> http://radicale:5232, rsync.freddieridell.com -> http://sync:8888'
      STAGE: staging
  sync:
    image: resilio/sync
    ports:
      - "55555:55555"
    restart: on-failure
    volumes:
      - '/docker/data/sync:/mnt/sync'
  #hypertask:
    #build: hypertask
    #ports:
      #- "15423:15423"
  radicale:
    build: radicale
    volumes:
      - /data
