version: "2"

services:
  #https-portal:
    #image: steveltn/https-portal:1
    #ports:
      #- '80:80'
      #- '443:443'
    #links:
      #- sync
    #restart: always
    #environment:
      #DOMAINS: 'sync.freddieridell.com -> http://sync:8888'
      #STAGE: local
    # FORCE_RENEW: 'true'
  #hypertask: 
    #build: hypertask
    #ports: 
      #- "15423:15423"
  #sync:
    #image: resilio/sync
    #ports:
      #- "55555:55555"
      #- "8888:8888"
    #restart: on-failure
    #volumes:
      #- /data
  #radicale:
    #build: radicale
    #volumes:
      #- /data
  #markserv:
    #build: markserv
  gitlab: 
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - '80:80'
        - '443:443'
        - '22:22'
      volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
