version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '80:80'
     - '443:443'
    links:
     - gitlab
    restart: always
    environment:
      DOMAINS: 'git.freddieridell.com -> http://gitlab:80'
      STAGE: local
      FORCE_RENEW: 'true'
  #hypertask:
    #build: hypertask
    #ports:
      #- "15423:15423"
  #sync:
    #image: resilio/sync
    #ports:
      #- "55555:55555"
      #- "8888:8888"
    #restart: on-failure
    #volumes:
      #- /data
  #radicale:
    #build: radicale
    #volumes:
      #- /data
  #markserv:
    #build: markserv
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git.freddieridell.com'
    ports:
      - '2222:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
