version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '80:80'
     - '443:443'
    links:
     - gitlab
     - sync
    restart: always
    environment:
      DOMAINS: 'gitlab.freddieridell.com -> http://gitlab:80, rsync.freddieridell.com -> http://sync:8888'
      STAGE: staging
  sync:
    image: resilio/sync
    ports:
      - "55555:55555"
    restart: on-failure
    volumes:
      - '/docker/data/sync:/mnt/sync'
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.freddieridell.com'
    ports:
      - '22:22'
    volumes:
      - '/docker/gitlab/config:/etc/gitlab'
      - '/docker/gitlab/logs:/var/log/gitlab'
      - '/docker/gitlab/data:/var/opt/gitlab'
  #hypertask:
    #build: hypertask
    #ports:
      #- "15423:15423"
  #radicale:
    #build: radicale
    #volumes:
      #- /data
  #markserv:
    #build: markserv
